---
name: core-platform-docs
description: ""
config:
  autoscaling:
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
      scaleUp:
        stabilizationWindowSeconds: 30
    enabled: true
    maxReplicas: 8
    minReplicas: 3
    targetCPUUtilizationPercentage: 80
  replicas: 3
  resources:
    limits:
      cpu: 125m
      memory: 384Mi
