baseURL = ''
languageCode = 'en-us'
title = 'Intergo Developer Platform'
theme = 'hugo-theme-learn'
enableEmoji = true
# Title separator -- defaults to ::
titleSeparator = "-"
[params]
  themeVariant = "cecg"
  environments = ["gcp-pre-dev", "gcp-dev", "gcp-prod"]
  company = "Intergo"
  org = "intergo"
  environmentRepo = "https://github.com/intergo/platform-environments"
  email_org = "intergotelecom.com"
  github_org = "intergo"
# Enable search
[outputs]
  home = [ "HTML", "RSS", "JSON"]
