baseURL = ''
languageCode = 'en-us'
title = 'CECG Core Platform'
theme = 'hugo-theme-learn'
enableEmoji = true
# Title separator -- defaults to ::
titleSeparator = "-"
[params]
  themeVariant = "cecg"
# Enable search
[outputs]
home = [ "HTML", "RSS", "JSON"]
