baseURL = ''
languageCode = 'en-us'
title = 'CECG Core Platform'
theme = 'hugo-theme-relearn'
enableEmoji = true

[outputs]
  home = [ "html", "rss", "print", "search", "searchpage"]
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

# Title separator -- defaults to ::
titleSeparator = "-"

[params]
  themeVariant = "cecg"
  customMermaidURL = "https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js"
  editURL = "https://github.com/coreeng/core-platform-docs/tree/main/content/"
  disableLandingPageButton = true
  alwaysopen = false
  collapsibleMenu = true
  disableRootBreadcrumb = false
  disableExplicitIndexURLs = false
  mermaidZoom = true
  # throw build error on broken links (warning for image linking as it's broken atm)
  include.errorlevel = "error"
  link.errorlevel = "error"
  openapi.errorlevel = "error"
  image.errorlevel = "warning"


