{{- $registry := .Values.registry | required ".Values.registry is required." -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-platform-docs
  labels:
    app.kubernetes.io/name: core-platform-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: core-platform-docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core-platform-docs
    spec:
      containers:
        - name: core-platform-docs
          image: "{{ $registry }}/{{ .Values.service.image }}:{{ .Values.service.tag }}"
          env:
            - name: LIVE_RELOAD
              value: "false"
            - name: BASE_URL
              value: "{{ .Values.subDomain }}.{{ .Values.domain }}"
          {{- if .Values.service.environmentVariables }}
            {{- range $key, $value := .Values.service.environmentVariables }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 8080
