name: core-platform-docs Fast Feedback

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: v
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}

  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    secrets:
      env_vars: ${{ secrets.env_vars }}
    with:
      app-name: core-platform-docs
      version: ${{ needs.version.outputs.version }}
      working-directory: ./

  dispatch-extended-tests:
    needs: [fastfeedback]
    if: github.ref == 'refs/heads/main' && needs.fastfeedback.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Dispatch Extended Tests Workflow
        run: |
          curl -L -s \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/core-platform-docs-extended-test.yaml/dispatches \
            -d '{"ref": "${{ github.ref }}", "inputs": {"trigger": "fast_feedback_success"}}'
