name: core-platform-docs Extended Test

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  id-token: write

jobs:
  get-latest-version:
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-extended-test.yaml@v1
    with:
      image-name: core-platform-docs

  extendedtests:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-extended-test.yaml@v1
    secrets:
      env_vars: ${{ secrets.env_vars }}
    with:
      app-name: core-platform-docs
      version: ${{ needs.get-latest-version.outputs.version }}
      version-prefix: v
      working-directory: ./

  dispatch-prod:
    needs: [extendedtests]
    if: github.ref == 'refs/heads/main' && needs.extendedtests.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Prod Workflow
        run: |
          curl -L -s \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/core-platform-docs-prod.yaml/dispatches \
            -d '{"ref": "${{ github.ref }}"}'
